### PR TITLE
es-LA.mjs

### PR DESCRIPTION
**Pull request by egeggarmy**
here is the spanish locale

### CODE REVIEW

**Comment by e3ndr** [comment]
Looks good! Fix your Github name and I'll merge.

**Comment by egeggarmy** [comment]
> Looks good! Fix your Github name and I'll merge.

hopefully i fixed it. if its still bad lmk

**Comment by e3ndr** [comment]
Thanks!

**Comment by egeggarmy** [comment]
found an error. at  "ui.greeting.hello": "Hola!",.
there’s supposed to be this character “¡” at the beginning.

**Comment by egeggarmy** [comment]
> found an error. at "ui.greeting.hello": "Hola!",.
> there’s supposed to be this character “¡” at the beginning.

fixed version:  "ui.greeting.hello": "¡Hola!",

**Comment by e3ndr** [comment]
[Fixed.](https://github.com/Casterlabs/Casterlabs/commit/5439273c654a1e099c428600d68f622cd4156e2e)

**Pull request merged**
